FROM registry.access.redhat.com/ubi9/python-312@sha256:b642db8b1f0f9dca7bbe6999db7ac4c96cf3036833fc344af092268afbb02893

LABEL org.opencontainers.image.source=https://github.com/eniac111/pretalx-container
LABEL org.opencontainers.image.description="Unofficical container image for pretalx"
LABEL org.opencontainers.image.licenses=APACHE-2.0

USER root
RUN dnf update -y \
    && mkdir -p /etc/pretalx /var/pretalx/data /var/pretalx/static \
    && chown -R 1001:0 /etc/pretalx /var/pretalx/data /var/pretalx/static

USER default

RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel gunicorn \
 && pip3 install --no-cache-dir --upgrade-strategy eager -U "pretalx[postgres,redis]"

VOLUME ["/etc/pretalx", "/var/pretalx/data", "/pretalx/static"]
EXPOSE 80

ENTRYPOINT ["pretalx"]
CMD ["/opt/app-root/bin/gunicorn", \ 
     "pretalx.wsgi", \
     "--name", "pretalx", \
     "--workers", "4", \
     "--max-requests", "1200", \ 
     "--max-requests-jitter", "50", \
     "--log-level", "info", \
     "--bind", "127.0.0.1:8345" \
     ]
